name: indonesia
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://github.com/yudaprama/indonesia.dart.git
author: Yuda Prama <yudapramad@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
